// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMtrNX2g5_HMwdF9qw5aG9xugSJtt-cPc',
    appId: '1:977471826811:android:18347dbb5484d46fb3ebde',
    messagingSenderId: '977471826811',
    projectId: 'globalwallet-emoney',
    storageBucket: 'globalwallet-emoney.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsW5f7lsmkHL9OXtLs8hKqnQvUZ4bfVd8',
    appId: '1:977471826811:ios:b68522d2a034d07db3ebde',
    messagingSenderId: '977471826811',
    projectId: 'globalwallet-emoney',
    storageBucket: 'globalwallet-emoney.firebasestorage.app',
    androidClientId: '977471826811-n7p37ja7k3p2q7eo743ia823lg9tj7eu.apps.googleusercontent.com',
    iosClientId: '977471826811-mbfdociegkh9oonaj06ilepum2vpj7r7.apps.googleusercontent.com',
    iosBundleId: 'com.example.globalwallet',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjBhIbz2yKjkgnhmuu-ZFQcpb7kdNtxsk',
    appId: '1:977471826811:web:92883504d7711276b3ebde',
    messagingSenderId: '977471826811',
    projectId: 'globalwallet-emoney',
    authDomain: 'globalwallet-emoney.firebaseapp.com',
    storageBucket: 'globalwallet-emoney.firebasestorage.app',
    measurementId: 'G-W27DMX6Q9Y',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsW5f7lsmkHL9OXtLs8hKqnQvUZ4bfVd8',
    appId: '1:977471826811:ios:b68522d2a034d07db3ebde',
    messagingSenderId: '977471826811',
    projectId: 'globalwallet-emoney',
    storageBucket: 'globalwallet-emoney.firebasestorage.app',
    androidClientId: '977471826811-n7p37ja7k3p2q7eo743ia823lg9tj7eu.apps.googleusercontent.com',
    iosClientId: '977471826811-mbfdociegkh9oonaj06ilepum2vpj7r7.apps.googleusercontent.com',
    iosBundleId: 'com.example.globalwallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjBhIbz2yKjkgnhmuu-ZFQcpb7kdNtxsk',
    appId: '1:977471826811:web:a9e8bfc22c62d843b3ebde',
    messagingSenderId: '977471826811',
    projectId: 'globalwallet-emoney',
    authDomain: 'globalwallet-emoney.firebaseapp.com',
    storageBucket: 'globalwallet-emoney.firebasestorage.app',
    measurementId: 'G-WGCKF86Q26',
  );
}
